
server:
  port: 8002
  #port: 20006
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  tomcat:
    uri-encoding: UTF-8
spring:
# 配置返回时间戳
  jackson:
      serialization:
        write-dates-as-timestamps: true
  application:
    name: client-activity
  http:
  # 编码设置
   encoding:
     force: true
     charset: UTF-8
     enable: true
  # 页面跳转
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  # 开启aop
  aop: true
  datasource:
    url: jdbc:mysql://39.96.6.123:3306/bq_mb_activity?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Simon_@1x
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 800
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 10
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
mybatis:
  mapper-locations: classpath:com/beiqi/mybatis/mapper/*.xml
logging:
  config: classpath:logback-spring.xml

