server:
  port: 8003
#  port: 20003
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.6.123:3306/bq_mb_consult?setUnicode=true&characterEncoding=utf8
    username: root
    password: Simon_@1x
    tomcat:
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
      serialization:
         write_dates_as_timestamps: true
  thymeleaf:
      mode: HTML
      cache: false
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html
      servlet:
        content-type: text/html
mybatis:
  mapper-locations: com/beiqi/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.beiqi.mybatis.model
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
debug: true
ribbon:
  eager-load:
    enabled: true
logging:
  level:
      org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-spring.xml

