
server:
  port: 8006
  #port: 20008
  tomcat:
    uri-encoding: UTF-8
spring:
  main:
    banner-mode: "off"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zefah8dycl0bn7464o.mysql.rds.aliyuncs.com/bq_mb_bjev?setUnicode=true&characterEncoding=utf8
    username: root
    password: Simon_@1x-P
    tomcat:
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: true
  #zipkin:
    #base-url: http://192.168.1.127:9411/
  sleuth:
    sampler:
      percentage: 1
mybatis:
  mapper-locations: com/beiqi/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.beiqi.mybatis.model
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
debug: true
logging:
  config: classpath:logback-spring.xml
