server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://handongkeji.com:3306/bq_mb_user?setUnicode=true&characterEncoding=utf8
    username: root
    password: Admin2015
    tomcat:
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
      serialization:
         write_dates_as_timestamps: true
mybatis:
  mapper-locations: com/beiqi/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.beiqi.mybatis.model
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
debug: true
ribbon:
  eager-load:
    enabled: true
logging:
  level:
      org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-spring.xml
