server:
  port: 8003
#  port: 20003
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8016/eureka
      #defaultZone: http://twoeureka:20001/eureka,http://oneeureka:20000/eureka
      #defaultZone: http://180.76.100.183:8016/eureka,http://180.76.100.183:8888/eureka
spring:
  application:
    name: client-consult
#  cloud:
#    inetutils:
#      ignoredInterfaces[0]:lo
#      ignoredInterfaces[1]:eth0
#      ignoredInterfaces[2]:eth1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://handongkeji.com:3306/bq_mb_consult?setUnicode=true&characterEncoding=utf8
    username: root
    password: Admin2015
    tomcat:
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
      serialization:
         write_dates_as_timestamps: true
  thymeleaf:
      mode: HTML
      cache: false
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html
      servlet:
        content-type: text/html


#  zipkin:
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      percentage: 1
mybatis:
  mapper-locations: com/beiqi/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.beiqi.mybatis.model
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
debug: true
ribbon:
  eager-load:
    enabled: true
logging:
  level:
      org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-spring.xml

