server:
  port: 20006
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: client-recommend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.6.123:3306/bq_mb_recommend?setUnicode=true&characterEncoding=utf8
    username: root
    password: Simon_@1x
    tomcat:
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
      serialization:
         write_dates_as_timestamps: true
  sleuth:
      sampler:
        percentage: 1
mybatis:
  mapper-locations: com/beiqi/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.beiqi.mybatis.model
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
debug: true
logging:
  config: classpath:lobback-spring.xml
